### PR TITLE
Fix output file Path.

### PR DESCRIPTION
**Pull request by mohsinenar**
Fix for issue: #125

### CODE REVIEW

**Review by SimonGurney — APPROVED** [review]

**Comment by SimonGurney** [comment]
I cant merge this in because you haven't signed the commit.  

If you sign it I will merge it in and you'll get the contributor link on the repo.  If not, I'll make the change on a branch here and merge it in?

**Comment by imnotbrandon** [comment]
I'm not sure if this is the correct approach. In general, when specifying a path as an argument to other tools, it takes the path verbatim. It should be up to the user to specify the full path and filename for the file, allowing them to add the extension themselves.

Personally, I don't think that we should be automatically adding the extension on the end in any circumstances. Things start to get messier when you deal with formats that have many different extensions (think of `.yml` and `.yaml`, `.htm` and `.html`).

I'd rather just accept the output path as-is.

**Comment by mohsinenar** [comment]
> I'm not sure if this is the correct approach. In general, when specifying a path as an argument to other tools, it takes the path verbatim. It should be up to the user to specify the full path and filename for the file, allowing them to add the extension themselves.
> 
> Personally, I don't think that we should be automatically adding the extension on the end in any circumstances. Things start to get messier when you deal with formats that have many different extensions (think of `.yml` and `.yaml`, `.htm` and `.html`).
> 
> I'd rather just accept the output path as-is.

I agree with you, however, the original behaviour was more confusing as the output bath will always have the extension automatically added even if the original bath already has an extension in it.
if you want I can update my PR to support keeping the bath as it is all the time.

**Comment by SimonGurney** [comment]
> > I'm not sure if this is the correct approach. In general, when specifying a path as an argument to other tools, it takes the path verbatim. It should be up to the user to specify the full path and filename for the file, allowing them to add the extension themselves.
> > Personally, I don't think that we should be automatically adding the extension on the end in any circumstances. Things start to get messier when you deal with formats that have many different extensions (think of `.yml` and `.yaml`, `.htm` and `.html`).
> > I'd rather just accept the output path as-is.
> 
> I agree with you, however, the original behaviour was more confusing as the output bath will always have the extension automatically added even if the original bath already has an extension in it. if you want I can update my PR to support keeping the bath as it is all the time.

That makes sense.  Can you amend the previous commit and sign it?  Signing is automatic if its done in the UI, but not sure if you can amend in the UI

**Comment by mohsinenar** [comment]
@SimonGurney amend required to force-push, I created a new PR here #135

**Pull request closed without merging**
