### PR TITLE
113 google cloud provider

### PR DESCRIPTION
**Pull request by VKotwicki**

### CODE REVIEW

**Review by imnotbrandon — APPROVED** [review]

**Comment by adamgross42** [comment]
Hi folks, it looks like this missed adding a Google Cloud package to `requirements.txt`.  Do you know which package that should be?  Otherwise it results in `ModuleNotFoundError: No module named 'google.cloud'`.

**Comment by SimonGurney** [comment]
Ah, nightmare.  Not sure how this got past our testing to be honest but we don't  automatically test providers.

I'll get it sorted, unless you want to raise a PR and get a contributor badge?

**Comment by adamgross42** [comment]
Sure, I can put up a PR, I think I found the package name.

**Comment by SimonGurney** [comment]
Thanks for sorting.  I'll push a tag tomorrow to update the docker image.  The nightly build should occur at midnight if you wanted to test it out before then.

**Comment by adamgross42** [comment]
I'm not using this within Docker, I have it working fine locally now, thanks!

**Pull request merged**
